// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cdac/delegation_policy.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelegationPolicy struct {
	Id                 uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label              string                  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Target             *DelegationPolicyTarget `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	CombiningAlgorithm string                  `protobuf:"bytes,4,opt,name=combiningAlgorithm,proto3" json:"combiningAlgorithm,omitempty"`
	RuleList           *DelegationRule         `protobuf:"bytes,5,opt,name=ruleList,proto3" json:"ruleList,omitempty"`
	Creator            string                  `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *DelegationPolicy) Reset()         { *m = DelegationPolicy{} }
func (m *DelegationPolicy) String() string { return proto.CompactTextString(m) }
func (*DelegationPolicy) ProtoMessage()    {}
func (*DelegationPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c422c169bdfb736, []int{0}
}
func (m *DelegationPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationPolicy.Merge(m, src)
}
func (m *DelegationPolicy) XXX_Size() int {
	return m.Size()
}
func (m *DelegationPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationPolicy proto.InternalMessageInfo

func (m *DelegationPolicy) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DelegationPolicy) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *DelegationPolicy) GetTarget() *DelegationPolicyTarget {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *DelegationPolicy) GetCombiningAlgorithm() string {
	if m != nil {
		return m.CombiningAlgorithm
	}
	return ""
}

func (m *DelegationPolicy) GetRuleList() *DelegationRule {
	if m != nil {
		return m.RuleList
	}
	return nil
}

func (m *DelegationPolicy) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*DelegationPolicy)(nil), "crossdomain.cdac.DelegationPolicy")
}

func init() { proto.RegisterFile("cdac/delegation_policy.proto", fileDescriptor_5c422c169bdfb736) }

var fileDescriptor_5c422c169bdfb736 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0xc4, 0x30,
	0x14, 0xc7, 0x2f, 0xf5, 0xae, 0x6a, 0x04, 0x39, 0x82, 0x43, 0x28, 0x12, 0x8a, 0x2e, 0x9d, 0x52,
	0x38, 0x57, 0x07, 0x15, 0x47, 0x07, 0x09, 0x4e, 0x2e, 0x47, 0x9a, 0x84, 0x1a, 0x48, 0x9b, 0x92,
	0xe6, 0xc0, 0x5b, 0xfd, 0x04, 0x7e, 0x2c, 0xc7, 0x1b, 0x1d, 0xa5, 0xfd, 0x22, 0x72, 0xa9, 0x1e,
	0x52, 0x0e, 0xc7, 0xc7, 0xff, 0xff, 0x7b, 0xbf, 0xc7, 0x83, 0xe7, 0x42, 0x72, 0x91, 0x4b, 0x65,
	0x54, 0xc9, 0xbd, 0xb6, 0xf5, 0xb2, 0xb1, 0x46, 0x8b, 0x35, 0x6d, 0x9c, 0xf5, 0x16, 0xcd, 0x85,
	0xb3, 0x6d, 0x2b, 0x6d, 0xc5, 0x75, 0x4d, 0xb7, 0xcd, 0xe4, 0x72, 0x7f, 0x7f, 0xe9, 0xb9, 0x2b,
	0x95, 0x1f, 0xb0, 0x24, 0x19, 0x97, 0xdc, 0xca, 0xa8, 0x21, 0xbb, 0x78, 0x8b, 0xe0, 0xfc, 0x7e,
	0x97, 0x3c, 0x06, 0x1a, 0x9d, 0xc2, 0x48, 0x4b, 0x0c, 0x52, 0x90, 0x4d, 0x59, 0xa4, 0x25, 0x3a,
	0x83, 0x33, 0xc3, 0x0b, 0x65, 0x70, 0x94, 0x82, 0xec, 0x98, 0x0d, 0x03, 0xba, 0x81, 0xf1, 0xa0,
	0xc1, 0x07, 0x29, 0xc8, 0x4e, 0x16, 0x19, 0x1d, 0x9f, 0x47, 0xc7, 0x9b, 0x9f, 0x42, 0x9f, 0xfd,
	0x70, 0x88, 0x42, 0x24, 0x6c, 0x55, 0xe8, 0x5a, 0xd7, 0xe5, 0xad, 0x29, 0xad, 0xd3, 0xfe, 0xa5,
	0xc2, 0xd3, 0x20, 0xd9, 0x93, 0xa0, 0x6b, 0x78, 0xb4, 0x3d, 0xfd, 0x41, 0xb7, 0x1e, 0xcf, 0x82,
	0x33, 0xfd, 0xcf, 0xc9, 0x56, 0x46, 0xb1, 0x1d, 0x81, 0x30, 0x3c, 0x14, 0x4e, 0x71, 0x6f, 0x1d,
	0x8e, 0x83, 0xe2, 0x77, 0xbc, 0x5b, 0x7c, 0x74, 0x04, 0x6c, 0x3a, 0x02, 0xbe, 0x3a, 0x02, 0xde,
	0x7b, 0x32, 0xd9, 0xf4, 0x64, 0xf2, 0xd9, 0x93, 0xc9, 0x33, 0xfe, 0xb3, 0x3e, 0x7f, 0xcd, 0xc3,
	0x23, 0xfd, 0xba, 0x51, 0x6d, 0x11, 0x87, 0xff, 0x5d, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe3,
	0x27, 0xbb, 0xdc, 0xb2, 0x01, 0x00, 0x00,
}

func (m *DelegationPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDelegationPolicy(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if m.RuleList != nil {
		{
			size, err := m.RuleList.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDelegationPolicy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CombiningAlgorithm) > 0 {
		i -= len(m.CombiningAlgorithm)
		copy(dAtA[i:], m.CombiningAlgorithm)
		i = encodeVarintDelegationPolicy(dAtA, i, uint64(len(m.CombiningAlgorithm)))
		i--
		dAtA[i] = 0x22
	}
	if m.Target != nil {
		{
			size, err := m.Target.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDelegationPolicy(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintDelegationPolicy(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintDelegationPolicy(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDelegationPolicy(dAtA []byte, offset int, v uint64) int {
	offset -= sovDelegationPolicy(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegationPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovDelegationPolicy(uint64(m.Id))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovDelegationPolicy(uint64(l))
	}
	if m.Target != nil {
		l = m.Target.Size()
		n += 1 + l + sovDelegationPolicy(uint64(l))
	}
	l = len(m.CombiningAlgorithm)
	if l > 0 {
		n += 1 + l + sovDelegationPolicy(uint64(l))
	}
	if m.RuleList != nil {
		l = m.RuleList.Size()
		n += 1 + l + sovDelegationPolicy(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDelegationPolicy(uint64(l))
	}
	return n
}

func sovDelegationPolicy(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDelegationPolicy(x uint64) (n int) {
	return sovDelegationPolicy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegationPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDelegationPolicy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Target == nil {
				m.Target = &DelegationPolicyTarget{}
			}
			if err := m.Target.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CombiningAlgorithm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CombiningAlgorithm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuleList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RuleList == nil {
				m.RuleList = &DelegationRule{}
			}
			if err := m.RuleList.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDelegationPolicy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDelegationPolicy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDelegationPolicy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDelegationPolicy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelegationPolicy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDelegationPolicy
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDelegationPolicy
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDelegationPolicy
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDelegationPolicy        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDelegationPolicy          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDelegationPolicy = fmt.Errorf("proto: unexpected end of group")
)
