// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cdac/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the cdac module's genesis state.
type GenesisState struct {
	Params                 Params              `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PortId                 string              `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	PublicKeyList          []PublicKey         `protobuf:"bytes,3,rep,name=publicKeyList,proto3" json:"publicKeyList"`
	PublicKeyCount         uint64              `protobuf:"varint,4,opt,name=publicKeyCount,proto3" json:"publicKeyCount,omitempty"`
	ValidityList           []Validity          `protobuf:"bytes,5,rep,name=validityList,proto3" json:"validityList"`
	ValidityCount          uint64              `protobuf:"varint,6,opt,name=validityCount,proto3" json:"validityCount,omitempty"`
	CertificateList        []Certificate       `protobuf:"bytes,7,rep,name=certificateList,proto3" json:"certificateList"`
	CertificateCount       uint64              `protobuf:"varint,8,opt,name=certificateCount,proto3" json:"certificateCount,omitempty"`
	IbcConnectionList      []IbcConnection     `protobuf:"bytes,9,rep,name=ibcConnectionList,proto3" json:"ibcConnectionList"`
	IbcConnectionCount     uint64              `protobuf:"varint,10,opt,name=ibcConnectionCount,proto3" json:"ibcConnectionCount,omitempty"`
	DomainList             []Domain            `protobuf:"bytes,11,rep,name=domainList,proto3" json:"domainList"`
	DomainCount            uint64              `protobuf:"varint,12,opt,name=domainCount,proto3" json:"domainCount,omitempty"`
	AuthenticationLogList  []AuthenticationLog `protobuf:"bytes,13,rep,name=authenticationLogList,proto3" json:"authenticationLogList"`
	AuthenticationLogCount uint64              `protobuf:"varint,14,opt,name=authenticationLogCount,proto3" json:"authenticationLogCount,omitempty"`
	DomainCooperationList  []DomainCooperation `protobuf:"bytes,15,rep,name=domainCooperationList,proto3" json:"domainCooperationList"`
	DomainCooperationCount uint64              `protobuf:"varint,16,opt,name=domainCooperationCount,proto3" json:"domainCooperationCount,omitempty"`
	CooperationLogList     []CooperationLog    `protobuf:"bytes,17,rep,name=cooperationLogList,proto3" json:"cooperationLogList"`
	CooperationLogCount    uint64              `protobuf:"varint,18,opt,name=cooperationLogCount,proto3" json:"cooperationLogCount,omitempty"`
	ForwardPolicyList      []ForwardPolicy     `protobuf:"bytes,19,rep,name=forwardPolicyList,proto3" json:"forwardPolicyList"`
	ForwardPolicyCount     uint64              `protobuf:"varint,20,opt,name=forwardPolicyCount,proto3" json:"forwardPolicyCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e370488142f36e, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetPublicKeyList() []PublicKey {
	if m != nil {
		return m.PublicKeyList
	}
	return nil
}

func (m *GenesisState) GetPublicKeyCount() uint64 {
	if m != nil {
		return m.PublicKeyCount
	}
	return 0
}

func (m *GenesisState) GetValidityList() []Validity {
	if m != nil {
		return m.ValidityList
	}
	return nil
}

func (m *GenesisState) GetValidityCount() uint64 {
	if m != nil {
		return m.ValidityCount
	}
	return 0
}

func (m *GenesisState) GetCertificateList() []Certificate {
	if m != nil {
		return m.CertificateList
	}
	return nil
}

func (m *GenesisState) GetCertificateCount() uint64 {
	if m != nil {
		return m.CertificateCount
	}
	return 0
}

func (m *GenesisState) GetIbcConnectionList() []IbcConnection {
	if m != nil {
		return m.IbcConnectionList
	}
	return nil
}

func (m *GenesisState) GetIbcConnectionCount() uint64 {
	if m != nil {
		return m.IbcConnectionCount
	}
	return 0
}

func (m *GenesisState) GetDomainList() []Domain {
	if m != nil {
		return m.DomainList
	}
	return nil
}

func (m *GenesisState) GetDomainCount() uint64 {
	if m != nil {
		return m.DomainCount
	}
	return 0
}

func (m *GenesisState) GetAuthenticationLogList() []AuthenticationLog {
	if m != nil {
		return m.AuthenticationLogList
	}
	return nil
}

func (m *GenesisState) GetAuthenticationLogCount() uint64 {
	if m != nil {
		return m.AuthenticationLogCount
	}
	return 0
}

func (m *GenesisState) GetDomainCooperationList() []DomainCooperation {
	if m != nil {
		return m.DomainCooperationList
	}
	return nil
}

func (m *GenesisState) GetDomainCooperationCount() uint64 {
	if m != nil {
		return m.DomainCooperationCount
	}
	return 0
}

func (m *GenesisState) GetCooperationLogList() []CooperationLog {
	if m != nil {
		return m.CooperationLogList
	}
	return nil
}

func (m *GenesisState) GetCooperationLogCount() uint64 {
	if m != nil {
		return m.CooperationLogCount
	}
	return 0
}

func (m *GenesisState) GetForwardPolicyList() []ForwardPolicy {
	if m != nil {
		return m.ForwardPolicyList
	}
	return nil
}

func (m *GenesisState) GetForwardPolicyCount() uint64 {
	if m != nil {
		return m.ForwardPolicyCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "crossdomain.cdac.GenesisState")
}

func init() { proto.RegisterFile("cdac/genesis.proto", fileDescriptor_c4e370488142f36e) }

var fileDescriptor_c4e370488142f36e = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x63, 0x5a, 0x52, 0xb2, 0x49, 0xda, 0x64, 0xd3, 0x16, 0x13, 0x54, 0xd7, 0x02, 0x84,
	0x22, 0x0e, 0x09, 0x0a, 0x52, 0x8f, 0x48, 0x34, 0x11, 0x55, 0x45, 0x91, 0xaa, 0x54, 0xea, 0x81,
	0x8b, 0xe5, 0xac, 0xb7, 0x61, 0x45, 0xea, 0xb5, 0xec, 0x0d, 0x90, 0xb7, 0xe0, 0xb1, 0x7a, 0xec,
	0x91, 0x13, 0xa0, 0xe4, 0x45, 0x90, 0x67, 0xd6, 0xa9, 0x1d, 0x3b, 0x37, 0xfb, 0xff, 0x67, 0xe6,
	0xfb, 0xb5, 0x1e, 0x2f, 0xa1, 0xcc, 0x73, 0x59, 0x6f, 0xc2, 0x7d, 0x1e, 0x89, 0xa8, 0x1b, 0x84,
	0x52, 0x49, 0xda, 0x60, 0xa1, 0x8c, 0x22, 0x4f, 0xde, 0xba, 0xc2, 0xef, 0xc6, 0x7e, 0x7b, 0x7f,
	0x22, 0x27, 0x12, 0xcc, 0x5e, 0xfc, 0x84, 0x75, 0xed, 0x26, 0xf4, 0x06, 0x6e, 0xe8, 0xde, 0xea,
	0xd6, 0xf6, 0x01, 0x4a, 0xb3, 0xf1, 0x54, 0x30, 0xe7, 0x1b, 0x9f, 0x6b, 0xb9, 0x05, 0xf2, 0x77,
	0x77, 0x2a, 0x3c, 0xa1, 0x12, 0xf1, 0x10, 0x44, 0xc6, 0x43, 0x25, 0x6e, 0x04, 0x73, 0x15, 0xd7,
	0xfa, 0x33, 0xd0, 0xc5, 0x98, 0x39, 0x4c, 0xfa, 0x3e, 0x67, 0x4a, 0x48, 0x3f, 0x43, 0xd4, 0xc9,
	0x50, 0x3a, 0x02, 0xc9, 0x9d, 0xa9, 0xaf, 0xdc, 0x57, 0xf1, 0x18, 0x21, 0x7d, 0x67, 0x2a, 0x27,
	0x19, 0x1b, 0x3b, 0x1c, 0x26, 0x65, 0xc0, 0x43, 0x37, 0x35, 0xb0, 0x8d, 0x19, 0x1e, 0xf4, 0x54,
	0x2b, 0xe6, 0xb8, 0x91, 0xe1, 0x0f, 0x37, 0xf4, 0x9c, 0x40, 0x4e, 0x05, 0xd3, 0xd1, 0x5f, 0xfc,
	0xad, 0x90, 0xda, 0x19, 0x9e, 0xd9, 0x95, 0x72, 0x15, 0xa7, 0x27, 0xa4, 0x8c, 0xe7, 0x60, 0x1a,
	0xb6, 0xd1, 0xa9, 0xf6, 0xcd, 0xee, 0xfa, 0x19, 0x76, 0x2f, 0xc1, 0x3f, 0xdd, 0xbe, 0xfb, 0x73,
	0x5c, 0x1a, 0xe9, 0x6a, 0xfa, 0x94, 0xec, 0x04, 0x32, 0x54, 0x8e, 0xf0, 0xcc, 0x47, 0xb6, 0xd1,
	0xa9, 0x8c, 0xca, 0xf1, 0xeb, 0xb9, 0x47, 0xcf, 0x48, 0x1d, 0x4f, 0xf1, 0x13, 0x9f, 0x5f, 0x88,
	0x48, 0x99, 0x5b, 0xf6, 0x56, 0xa7, 0xda, 0x7f, 0x5e, 0x30, 0x37, 0x29, 0xd3, 0xa3, 0xb3, 0x7d,
	0xf4, 0x35, 0xd9, 0x5d, 0x09, 0x03, 0x39, 0xf3, 0x95, 0xb9, 0x6d, 0x1b, 0x9d, 0xed, 0xd1, 0x9a,
	0x4a, 0x87, 0xa4, 0x96, 0x7c, 0x1f, 0xe0, 0x3d, 0x06, 0x5e, 0x3b, 0xcf, 0xbb, 0xd6, 0x55, 0x1a,
	0x97, 0xe9, 0xa2, 0xaf, 0x48, 0x3d, 0x79, 0x47, 0x58, 0x19, 0x60, 0x59, 0x91, 0x7e, 0x26, 0x7b,
	0xa9, 0xcf, 0x0e, 0xb8, 0x1d, 0xc0, 0x1d, 0xe5, 0x71, 0x83, 0x87, 0x42, 0x4d, 0x5c, 0xef, 0xa5,
	0x6f, 0x48, 0x23, 0x25, 0x21, 0xf7, 0x09, 0x70, 0x73, 0x3a, 0xbd, 0x22, 0x4d, 0x31, 0x66, 0x83,
	0xd5, 0x62, 0x01, 0xbc, 0x02, 0xf0, 0xe3, 0x3c, 0xfc, 0x3c, 0x5d, 0xaa, 0xf1, 0xf9, 0x7e, 0xda,
	0x25, 0x34, 0x23, 0x62, 0x04, 0x02, 0x11, 0x0a, 0x1c, 0xfa, 0x9e, 0x10, 0xa4, 0x00, 0xbd, 0x0a,
	0xf4, 0x82, 0x8d, 0x19, 0xc2, 0xb3, 0xc6, 0xa6, 0x3a, 0xa8, 0x4d, 0xaa, 0xf8, 0x86, 0xa0, 0x1a,
	0x80, 0xd2, 0x12, 0x75, 0xc8, 0x41, 0xf6, 0x97, 0xb8, 0x90, 0x13, 0x80, 0xd5, 0x01, 0xf6, 0x32,
	0x0f, 0xfb, 0xb0, 0x5e, 0xae, 0xb9, 0xc5, 0x73, 0xe8, 0x09, 0x39, 0xcc, 0x19, 0x98, 0x66, 0x17,
	0xd2, 0x6c, 0x70, 0xe3, 0x60, 0x49, 0xce, 0xd5, 0x3f, 0x07, 0xc1, 0xf6, 0x36, 0x05, 0x1b, 0xae,
	0x97, 0x27, 0xc1, 0x0a, 0xe7, 0xc4, 0xc1, 0x72, 0x06, 0x06, 0x6b, 0x60, 0xb0, 0x62, 0x97, 0x5e,
	0x13, 0x9a, 0xba, 0x06, 0x92, 0xe3, 0x6a, 0x42, 0x2a, 0xbb, 0x60, 0x2d, 0x33, 0xb5, 0x3a, 0x52,
	0xc1, 0x04, 0xfa, 0x96, 0xb4, 0xb2, 0x2a, 0x86, 0xa1, 0x10, 0xa6, 0xc8, 0x8a, 0x57, 0x54, 0x5f,
	0x3a, 0x97, 0x70, 0xe7, 0x40, 0x90, 0xd6, 0xa6, 0x15, 0xfd, 0x98, 0x2e, 0x4d, 0x56, 0x34, 0xd7,
	0x1f, 0xaf, 0x68, 0x46, 0xc4, 0x14, 0xfb, 0xb8, 0xa2, 0x79, 0xe7, 0xb4, 0x7f, 0xb7, 0xb0, 0x8c,
	0xfb, 0x85, 0x65, 0xfc, 0x5b, 0x58, 0xc6, 0xaf, 0xa5, 0x55, 0xba, 0x5f, 0x5a, 0xa5, 0xdf, 0x4b,
	0xab, 0xf4, 0xc5, 0x4c, 0x45, 0xe8, 0xfd, 0xec, 0xc1, 0x25, 0xa9, 0xe6, 0x01, 0x8f, 0xc6, 0x65,
	0xb8, 0x1c, 0xdf, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x6a, 0x13, 0xef, 0x54, 0x06, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ForwardPolicyCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ForwardPolicyCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if len(m.ForwardPolicyList) > 0 {
		for iNdEx := len(m.ForwardPolicyList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ForwardPolicyList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x9a
		}
	}
	if m.CooperationLogCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CooperationLogCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.CooperationLogList) > 0 {
		for iNdEx := len(m.CooperationLogList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CooperationLogList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if m.DomainCooperationCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DomainCooperationCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.DomainCooperationList) > 0 {
		for iNdEx := len(m.DomainCooperationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DomainCooperationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	if m.AuthenticationLogCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AuthenticationLogCount))
		i--
		dAtA[i] = 0x70
	}
	if len(m.AuthenticationLogList) > 0 {
		for iNdEx := len(m.AuthenticationLogList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuthenticationLogList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.DomainCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DomainCount))
		i--
		dAtA[i] = 0x60
	}
	if len(m.DomainList) > 0 {
		for iNdEx := len(m.DomainList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DomainList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.IbcConnectionCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.IbcConnectionCount))
		i--
		dAtA[i] = 0x50
	}
	if len(m.IbcConnectionList) > 0 {
		for iNdEx := len(m.IbcConnectionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.IbcConnectionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.CertificateCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CertificateCount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CertificateList) > 0 {
		for iNdEx := len(m.CertificateList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CertificateList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.ValidityCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ValidityCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ValidityList) > 0 {
		for iNdEx := len(m.ValidityList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidityList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.PublicKeyCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PublicKeyCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PublicKeyList) > 0 {
		for iNdEx := len(m.PublicKeyList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PublicKeyList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PublicKeyList) > 0 {
		for _, e := range m.PublicKeyList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PublicKeyCount != 0 {
		n += 1 + sovGenesis(uint64(m.PublicKeyCount))
	}
	if len(m.ValidityList) > 0 {
		for _, e := range m.ValidityList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ValidityCount != 0 {
		n += 1 + sovGenesis(uint64(m.ValidityCount))
	}
	if len(m.CertificateList) > 0 {
		for _, e := range m.CertificateList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CertificateCount != 0 {
		n += 1 + sovGenesis(uint64(m.CertificateCount))
	}
	if len(m.IbcConnectionList) > 0 {
		for _, e := range m.IbcConnectionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.IbcConnectionCount != 0 {
		n += 1 + sovGenesis(uint64(m.IbcConnectionCount))
	}
	if len(m.DomainList) > 0 {
		for _, e := range m.DomainList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DomainCount != 0 {
		n += 1 + sovGenesis(uint64(m.DomainCount))
	}
	if len(m.AuthenticationLogList) > 0 {
		for _, e := range m.AuthenticationLogList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.AuthenticationLogCount != 0 {
		n += 1 + sovGenesis(uint64(m.AuthenticationLogCount))
	}
	if len(m.DomainCooperationList) > 0 {
		for _, e := range m.DomainCooperationList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DomainCooperationCount != 0 {
		n += 2 + sovGenesis(uint64(m.DomainCooperationCount))
	}
	if len(m.CooperationLogList) > 0 {
		for _, e := range m.CooperationLogList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if m.CooperationLogCount != 0 {
		n += 2 + sovGenesis(uint64(m.CooperationLogCount))
	}
	if len(m.ForwardPolicyList) > 0 {
		for _, e := range m.ForwardPolicyList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if m.ForwardPolicyCount != 0 {
		n += 2 + sovGenesis(uint64(m.ForwardPolicyCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKeyList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKeyList = append(m.PublicKeyList, PublicKey{})
			if err := m.PublicKeyList[len(m.PublicKeyList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKeyCount", wireType)
			}
			m.PublicKeyCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublicKeyCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidityList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidityList = append(m.ValidityList, Validity{})
			if err := m.ValidityList[len(m.ValidityList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidityCount", wireType)
			}
			m.ValidityCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidityCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertificateList = append(m.CertificateList, Certificate{})
			if err := m.CertificateList[len(m.CertificateList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateCount", wireType)
			}
			m.CertificateCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcConnectionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcConnectionList = append(m.IbcConnectionList, IbcConnection{})
			if err := m.IbcConnectionList[len(m.IbcConnectionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcConnectionCount", wireType)
			}
			m.IbcConnectionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IbcConnectionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DomainList = append(m.DomainList, Domain{})
			if err := m.DomainList[len(m.DomainList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainCount", wireType)
			}
			m.DomainCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DomainCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticationLogList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthenticationLogList = append(m.AuthenticationLogList, AuthenticationLog{})
			if err := m.AuthenticationLogList[len(m.AuthenticationLogList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticationLogCount", wireType)
			}
			m.AuthenticationLogCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuthenticationLogCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainCooperationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DomainCooperationList = append(m.DomainCooperationList, DomainCooperation{})
			if err := m.DomainCooperationList[len(m.DomainCooperationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainCooperationCount", wireType)
			}
			m.DomainCooperationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DomainCooperationCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CooperationLogList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CooperationLogList = append(m.CooperationLogList, CooperationLog{})
			if err := m.CooperationLogList[len(m.CooperationLogList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CooperationLogCount", wireType)
			}
			m.CooperationLogCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CooperationLogCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForwardPolicyList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForwardPolicyList = append(m.ForwardPolicyList, ForwardPolicy{})
			if err := m.ForwardPolicyList[len(m.ForwardPolicyList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForwardPolicyCount", wireType)
			}
			m.ForwardPolicyCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForwardPolicyCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
