// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crossdomain/cooperation_network_features.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CooperationNetworkFeatures struct {
	Depth        uint64    `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Cost         uint64    `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	InterestList []string  `protobuf:"bytes,3,rep,name=interestList,proto3" json:"interestList,omitempty"`
	LocationList []string  `protobuf:"bytes,4,rep,name=locationList,proto3" json:"locationList,omitempty"`
	LastUpdate   string    `protobuf:"bytes,5,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	Validity     *Validity `protobuf:"bytes,6,opt,name=validity,proto3" json:"validity,omitempty"`
	Creator      string    `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *CooperationNetworkFeatures) Reset()         { *m = CooperationNetworkFeatures{} }
func (m *CooperationNetworkFeatures) String() string { return proto.CompactTextString(m) }
func (*CooperationNetworkFeatures) ProtoMessage()    {}
func (*CooperationNetworkFeatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c71c825d167cc9b, []int{0}
}
func (m *CooperationNetworkFeatures) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CooperationNetworkFeatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CooperationNetworkFeatures.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CooperationNetworkFeatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CooperationNetworkFeatures.Merge(m, src)
}
func (m *CooperationNetworkFeatures) XXX_Size() int {
	return m.Size()
}
func (m *CooperationNetworkFeatures) XXX_DiscardUnknown() {
	xxx_messageInfo_CooperationNetworkFeatures.DiscardUnknown(m)
}

var xxx_messageInfo_CooperationNetworkFeatures proto.InternalMessageInfo

func (m *CooperationNetworkFeatures) GetDepth() uint64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *CooperationNetworkFeatures) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *CooperationNetworkFeatures) GetInterestList() []string {
	if m != nil {
		return m.InterestList
	}
	return nil
}

func (m *CooperationNetworkFeatures) GetLocationList() []string {
	if m != nil {
		return m.LocationList
	}
	return nil
}

func (m *CooperationNetworkFeatures) GetLastUpdate() string {
	if m != nil {
		return m.LastUpdate
	}
	return ""
}

func (m *CooperationNetworkFeatures) GetValidity() *Validity {
	if m != nil {
		return m.Validity
	}
	return nil
}

func (m *CooperationNetworkFeatures) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*CooperationNetworkFeatures)(nil), "crossdomain.crossdomain.CooperationNetworkFeatures")
}

func init() {
	proto.RegisterFile("crossdomain/cooperation_network_features.proto", fileDescriptor_1c71c825d167cc9b)
}

var fileDescriptor_1c71c825d167cc9b = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe3, 0x36, 0x6d, 0xbf, 0xfa, 0x63, 0xb2, 0x90, 0xb0, 0x32, 0x98, 0xd0, 0x29, 0x53,
	0x2a, 0xc1, 0xc4, 0xc0, 0x02, 0x12, 0x13, 0x62, 0x88, 0x04, 0x03, 0x4b, 0x65, 0x12, 0x23, 0x2c,
	0x42, 0x8e, 0x65, 0x1f, 0x7e, 0x7a, 0x05, 0xac, 0x5c, 0x16, 0x63, 0x47, 0x46, 0x94, 0xdc, 0x08,
	0xc2, 0x69, 0xc1, 0x0c, 0x6c, 0x3e, 0xaf, 0x9e, 0xf7, 0xb1, 0xce, 0xa1, 0x79, 0x69, 0xc1, 0xb9,
	0x0a, 0xee, 0xa5, 0x6e, 0xe6, 0x25, 0x80, 0x51, 0x56, 0xa2, 0x86, 0x66, 0xd1, 0x28, 0x7c, 0x02,
	0x7b, 0xb7, 0xb8, 0x51, 0x12, 0x1f, 0xac, 0x72, 0xb9, 0xb1, 0x80, 0xc0, 0x76, 0x02, 0x3e, 0xec,
	0x26, 0x49, 0x28, 0x7a, 0x94, 0xb5, 0xae, 0x34, 0x2e, 0xfb, 0xd2, 0xec, 0x65, 0x40, 0x93, 0x93,
	0x1f, 0xf7, 0x79, 0xaf, 0x3e, 0x5d, 0x9b, 0xd9, 0x36, 0x1d, 0x55, 0xca, 0xe0, 0x2d, 0x27, 0x29,
	0xc9, 0xe2, 0xa2, 0x1f, 0x18, 0xa3, 0x71, 0x09, 0x0e, 0xf9, 0xc0, 0x87, 0xfe, 0xcd, 0x66, 0x74,
	0x4b, 0x37, 0xa8, 0xac, 0x72, 0x78, 0xa6, 0x1d, 0xf2, 0x61, 0x3a, 0xcc, 0xa6, 0xc5, 0xaf, 0xec,
	0x8b, 0xa9, 0xa1, 0xf4, 0x1f, 0x79, 0x26, 0xee, 0x99, 0x30, 0x63, 0x82, 0xd2, 0x5a, 0x3a, 0xbc,
	0x30, 0x95, 0x44, 0xc5, 0x47, 0x29, 0xc9, 0xa6, 0x45, 0x90, 0xb0, 0x23, 0xfa, 0x6f, 0xb3, 0x02,
	0x1f, 0xa7, 0x24, 0xfb, 0xbf, 0xbf, 0x97, 0xff, 0xb1, 0x78, 0x7e, 0xb9, 0x06, 0x8b, 0xef, 0x0a,
	0xe3, 0x74, 0x52, 0x5a, 0x25, 0x11, 0x2c, 0x9f, 0x78, 0xf7, 0x66, 0x3c, 0x3e, 0x7c, 0x6b, 0x05,
	0x59, 0xb5, 0x82, 0x7c, 0xb4, 0x82, 0xbc, 0x76, 0x22, 0x5a, 0x75, 0x22, 0x7a, 0xef, 0x44, 0x74,
	0xb5, 0x1b, 0xde, 0xef, 0x79, 0x1e, 0x4e, 0xb8, 0x34, 0xca, 0x5d, 0x8f, 0xfd, 0x2d, 0x0f, 0x3e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x81, 0xae, 0x7b, 0xdf, 0xb2, 0x01, 0x00, 0x00,
}

func (m *CooperationNetworkFeatures) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CooperationNetworkFeatures) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CooperationNetworkFeatures) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCooperationNetworkFeatures(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Validity != nil {
		{
			size, err := m.Validity.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCooperationNetworkFeatures(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.LastUpdate) > 0 {
		i -= len(m.LastUpdate)
		copy(dAtA[i:], m.LastUpdate)
		i = encodeVarintCooperationNetworkFeatures(dAtA, i, uint64(len(m.LastUpdate)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LocationList) > 0 {
		for iNdEx := len(m.LocationList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.LocationList[iNdEx])
			copy(dAtA[i:], m.LocationList[iNdEx])
			i = encodeVarintCooperationNetworkFeatures(dAtA, i, uint64(len(m.LocationList[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.InterestList) > 0 {
		for iNdEx := len(m.InterestList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.InterestList[iNdEx])
			copy(dAtA[i:], m.InterestList[iNdEx])
			i = encodeVarintCooperationNetworkFeatures(dAtA, i, uint64(len(m.InterestList[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Cost != 0 {
		i = encodeVarintCooperationNetworkFeatures(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x10
	}
	if m.Depth != 0 {
		i = encodeVarintCooperationNetworkFeatures(dAtA, i, uint64(m.Depth))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCooperationNetworkFeatures(dAtA []byte, offset int, v uint64) int {
	offset -= sovCooperationNetworkFeatures(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CooperationNetworkFeatures) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Depth != 0 {
		n += 1 + sovCooperationNetworkFeatures(uint64(m.Depth))
	}
	if m.Cost != 0 {
		n += 1 + sovCooperationNetworkFeatures(uint64(m.Cost))
	}
	if len(m.InterestList) > 0 {
		for _, s := range m.InterestList {
			l = len(s)
			n += 1 + l + sovCooperationNetworkFeatures(uint64(l))
		}
	}
	if len(m.LocationList) > 0 {
		for _, s := range m.LocationList {
			l = len(s)
			n += 1 + l + sovCooperationNetworkFeatures(uint64(l))
		}
	}
	l = len(m.LastUpdate)
	if l > 0 {
		n += 1 + l + sovCooperationNetworkFeatures(uint64(l))
	}
	if m.Validity != nil {
		l = m.Validity.Size()
		n += 1 + l + sovCooperationNetworkFeatures(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCooperationNetworkFeatures(uint64(l))
	}
	return n
}

func sovCooperationNetworkFeatures(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCooperationNetworkFeatures(x uint64) (n int) {
	return sovCooperationNetworkFeatures(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CooperationNetworkFeatures) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCooperationNetworkFeatures
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CooperationNetworkFeatures: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CooperationNetworkFeatures: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depth", wireType)
			}
			m.Depth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Depth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InterestList = append(m.InterestList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocationList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocationList = append(m.LocationList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastUpdate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Validity == nil {
				m.Validity = &Validity{}
			}
			if err := m.Validity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCooperationNetworkFeatures(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCooperationNetworkFeatures
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCooperationNetworkFeatures(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCooperationNetworkFeatures
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCooperationNetworkFeatures
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCooperationNetworkFeatures
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCooperationNetworkFeatures
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCooperationNetworkFeatures
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCooperationNetworkFeatures        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCooperationNetworkFeatures          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCooperationNetworkFeatures = fmt.Errorf("proto: unexpected end of group")
)
